include: package:very_good_analysis/analysis_options.6.0.0.yaml

analyzer:
  exclude:
    - lib/**.freezed.dart
    - lib/**.g.dart

linter:
  rules:
    public_member_api_docs: false
    specify_nonobvious_property_types: false

formatter:
  trailing_commas: preserve